const US_EQUITY_SECTOR_BY_ID = Object.freeze({
  "XNAS:AAPL": "Technology",
  "XNAS:MSFT": "Technology",
  "XNAS:NVDA": "Technology",
  "XNAS:GOOGL": "Communication Services",
  "XNAS:AMZN": "Consumer Discretionary",
  "XNAS:META": "Communication Services",
  "XNAS:TSLA": "Consumer Discretionary",
  "XNAS:AVGO": "Technology",
  "XNAS:COST": "Consumer Staples",
  "XNAS:NFLX": "Communication Services",
  "XNAS:AMD": "Technology",
  "XNAS:CSCO": "Technology",
  "XNYS:JPM": "Financials",
  "XNYS:V": "Financials",
  "XNYS:MA": "Financials",
  "XNYS:UNH": "Health Care",
  "XNYS:JNJ": "Health Care",
  "XNAS:WMT": "Consumer Staples",
  "XNYS:XOM": "Energy",
  "XNYS:CVX": "Energy",
  "XNYS:HD": "Consumer Discretionary",
  "XNYS:KO": "Consumer Staples",
  "XNYS:MCD": "Consumer Discretionary",
  "XNYS:DIS": "Communication Services",
  "XNYS:ORCL": "Technology",
  "XNYS:CRM": "Technology",
  "XNAS:ADBE": "Technology",
  "XNAS:QCOM": "Technology",
  "XNYS:BAC": "Financials",
  "XNYS:GS": "Financials",
  "XNYS:LLY": "Health Care",
  "XNYS:MRK": "Health Care",
  "XNYS:ABBV": "Health Care",
  "XNYS:PG": "Consumer Staples",
  "XNAS:PEP": "Consumer Staples",
  "XNYS:CAT": "Industrials",
  "XNYS:GE": "Industrials",
  "XNYS:BA": "Industrials",
  "XNYS:NEE": "Utilities",
  "XNAS:LIN": "Materials",
});

export function canonicalUsEquitySector(instrumentId) {
  if (typeof instrumentId !== "string") return null;
  return US_EQUITY_SECTOR_BY_ID[instrumentId.trim().toUpperCase()] || null;
}
