import { readFile, rm, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import process from "node:process";
import { build } from "esbuild";

const require = createRequire(import.meta.url);

function stripDsFontFaces(css) {
  const stripped = css.replace(/@font-face\s*{[^}]*}/g, "");
  if (stripped.includes("url(")) {
    throw new Error("ds styles.scoped.css transform: unexpected asset reference survived the font strip");
  }
  return stripped;
}

const stripDsFonts = {
  name: "strip-ds-fonts",
  setup(pluginBuild) {
    pluginBuild.onResolve({ filter: /^@ciavalabs\/ds-react\/styles\.scoped\.css$/ }, (args) => {
      const resolved = require.resolve(args.path, { paths: [args.resolveDir] });
      return { path: resolved, namespace: "ds-styles" };
    });
    pluginBuild.onLoad({ filter: /.*/, namespace: "ds-styles" }, async (args) => ({
      contents: stripDsFontFaces(await readFile(args.path, "utf8")),
      loader: "css",
    }));
  },
};

const LIB_ISLANDS = [
  ["ConsoleActions", "src/react/ConsoleActions.jsx", "ConsoleActions"],
  ["Toolbar", "src/react/Toolbar.jsx", "Toolbar"],
  ["AddInstrument", "src/react/AddInstrumentDialog.jsx", "AddInstrumentDialog"],
  ["InstrumentDetail", "src/react/InstrumentDetail.jsx", "InstrumentDetail"],
  ["ToastHost", "src/react/ToastHost.jsx", "ToastHost"],
  ["AssetGrid", "src/react/AssetGrid.jsx", "AssetGrid"],
];

const targets = {
  "--lib": {
    entryPoints: Object.fromEntries(LIB_ISLANDS.map(([out, src]) => [out, src])),
    outdir: "dist-react",
    bundle: true,
    format: "esm",
    packages: "external",
    jsx: "automatic",
    banner: { js: "// Generated by scripts/build-react.mjs — do not edit." },
  },
  "--demo": {
    entryPoints: {
      "console-actions": "src/react/consoleActions.entry.jsx",
      "toolbar": "src/react/toolbar.entry.jsx",
      "add-instrument": "src/react/addInstrument.entry.jsx",
      "instrument-detail": "src/react/instrumentDetail.entry.jsx",
      "toast-host": "src/react/toastHost.entry.jsx",
      "asset-grid": "src/react/assetGrid.entry.jsx",
    },
    outdir: "assets/react",
    bundle: true,
    splitting: true,
    format: "esm",
    minify: true,
    jsx: "automatic",
    define: { "process.env.NODE_ENV": '"production"' },
    plugins: [stripDsFonts],
  },
};

const requested = process.argv.slice(2);
const unknown = requested.filter((flag) => !(flag in targets));
if (unknown.length || !requested.length) {
  console.error(`Usage: node scripts/build-react.mjs [--lib] [--demo]`);
  process.exit(1);
}
for (const flag of requested) {
  const target = targets[flag];
  await rm(new URL(`../${target.outdir}/`, import.meta.url), { recursive: true, force: true });
  await build({ ...target, logLevel: "info" });
}

if (requested.includes("--lib")) {
  const barrel = [
    "// Generated by scripts/build-react.mjs — do not edit.",
    ...LIB_ISLANDS.map(([file, , name]) => `export { ${name} } from "./${file}.js";`),
    "",
  ].join("\n");
  await writeFile(new URL("../dist-react/index.js", import.meta.url), barrel);
  console.log(`  dist-react/index.js             ${Buffer.byteLength(barrel)}b  (barrel)`);
}
